const columnDefs= [
    { headerName: "Proprty", field: "proprty" , resizable: true , width: 420},
    { headerName: "Value", field: "value" , resizable: true , width: 300},
    
  ],
  rowDatachemical= [[[{ proprty: "Field", value: "Brintnell Field Horsetail"},
    { proprty: "Pool Name", value: "Upper Wabiskaw Sand"},
    { proprty: "Formation", value: "Wabiskaw-McMurray Deposit"},
    { proprty: "country", value: "Canada"},
    { proprty: "EOR Type", value: "Chemical EOR"},
    { proprty: "EOR Sub Type", value: "Polymer"},
    { proprty: "Flood Type", value: ""},
    { proprty: "Number of Wells", value: 5},
    { proprty: "Number of EOR Injectors", value: 2},
    { proprty: "Number of EOR Producers", value: 3},
    { proprty: "Date", value: ""},
    { proprty: "Discovery Date", value: ""},
    { proprty: "EOR start year", value: 2005},
    { proprty: "Secondary Recovery", value: ""}, 
    { proprty: "EOR 1", value: "Approval 10147 - Polymer Pilot Wells - HTLP 6 Polymer Flood(May 2005)"},
    { proprty: "EOR 2", value: "Approval 10423 - 1st area expanded after the pilot, polymer started 2007, expanded through 2010"},
    { proprty: "EOR 3", value: "Approval 10797 - Small area of polymer started in 2007 - 1st area to have multilateral well flooded by several injectors"},
    { proprty: "EOR 4", value: "Approval 9673"},
    { proprty: "Reservoir Fluid Properties and Reservoir Parameters", value: ""},
    { proprty: "Depth (m)", value: 360},
    { proprty: "Average Pay Thickness (m)", value: 5},
    { proprty: "Average Permeability (md)", value: 1400},
    { proprty: "Average Porosity", value: 0.3},
    { proprty: "Water Saturation", value: 0.35},
    { proprty: "Lithology", value: "Sandstone"},
    { proprty: "Initial Pressure (kPa)", value: 2200},
    { proprty: "Initial Temperature (C)", value: 15},
    { proprty: "Oil Gravity (API)", value: 10},
    { proprty: "Oil Density (kg/m3)", value: 1000},
    { proprty: "Oil Viscosity @ 15C (cp)", value: 144543.98},
    { proprty: "Oil Viscosity @ Tr (cp)", value: 144544.78},
    { proprty: "Salinity of Formation Water (ppm)", value: ""},
    { proprty: "Presence of Natural Fractures", value: ""},
    { proprty: "Presence of Gas Cap", value: ""},
    { proprty: "", value: ""},
    { proprty: "Oil Reserves (as of Dec 31, 2010)", value: ""},
    { proprty: "Area of Project (ha)", value: ""},
    { proprty: "Primary Recovery Factor (fraction)", value: ""},
    { proprty: "Incremental WF Recovery Factor (fraction)", value: ""},
    { proprty: "Incremental EOR Recovery Factor (fraction)", value: ""},
    { proprty: "Total Recovery Factor (fraction)", value: ""},
    { proprty: "OOIP (E3m3)", value: ""},
    { proprty: "Remaining Oil in-Place (E3m3) after Primary & EOR Recovery", value: ""},
    { proprty: "Remaining Recoverable Reserves (E3m3)", value: ""},
    ],
    
    [{proprty: "Field", value: "Cessford"},    
    { proprty: "Pool Name", value: "Cessford Basal Colorado 'A' Pool"},
    { proprty: "Formation", value: "Basal Colorado"},
    { proprty: "country", value: "Canada"},
    { proprty: "EOR Type", value: "Chemical EOR"},
    { proprty: "EOR Sub Type", value: "AP"},
    { proprty: "Flood Type", value: ""},
    { proprty: "Number of Wells", value: 26},
    { proprty: "Number of EOR Injectors", value: 7},
    { proprty: "Number of EOR Producers", value: 19},
    { proprty: "Date", value: ""},
    { proprty: "Discovery Date", value: 1958},
    { proprty: "EOR start year", value: 1984},
    { proprty: "Secondary Recovery", value: "Waterflood 81/02"},
    { proprty: "EOR 1", value: "Inject Preflush 83/12-84/07 North & Central Areas"},
    { proprty: "EOR 2", value: "Alkali Flood North & Central Area 84/07 - 85/05"},
    { proprty: "EOR 3", value: "Alkali/Polymer Flood in South 85/01"},
    { proprty: "EOR 4", value: "Alkali/Pol mer Flood in North & Central Patterns 85/05 Alkali/Polymer"},
    { proprty: "Reservoir Fluid Properties and Reservoir Parameters", value: ""},
    { proprty: "Depth (m)", value: 920},
    { proprty: "Average Pay Thickness (m)", value: 5},
    { proprty: "Average Permeability (md)", value: 350},
    { proprty: "Average Porosity", value: 0.24},
    { proprty: "Water Saturation", value: 0.30},
    { proprty: "Lithology", value: "Sandstone"},
    { proprty: "Initial Pressure (kPa)", value: 8784},
    { proprty: "Initial Temperature (C)", value: 26},
    { proprty: "Oil Gravity (API)", value: 23},
    { proprty: "Oil Density (kg/m3)", value: 915.9},
    { proprty: "Oil Viscosity @ 15C (cp)", value: 110.95},
    { proprty: "Oil Viscosity @ Tr (cp)", value: 1.00},
    { proprty: "Salinity of Formation Water (ppm)", value: ""},
    { proprty: "Presence of Natural Fractures", value: ""},
    { proprty: "Presence of Gas Cap", value: "Yes"},
    { proprty: "", value: ""},
    { proprty: "Oil Reserves (as of Dec 31, 2010)", value: ""},
    { proprty: "Area of Project (ha)", value: 303.5},
    { proprty: "Primary Recovery Factor (fraction)", value: ""},
    { proprty: "Incremental WF Recovery Factor (fraction)", value: ""},
    { proprty: "Incremental EOR Recovery Factor (fraction)", value: ""},
    { proprty: "Total Recovery Factor (fraction)", value: ""},
    { proprty: "OOIP (E3m3)", value: 17400},
    { proprty: "Remaining Oil in-Place (E3m3) after Primary & EOR Recovery", value: ""},
    { proprty: "Remaining Recoverable Reserves (E3m3)", value: ""},
    ],
    
    [{proprty: "Field", value: "Chauvin South"},    
    { proprty: "Pool Name", value: "Sparky E"},
    { proprty: "Formation", value: "Sparky E"},
    { proprty: "country", value: "Canada"},
    { proprty: "EOR Type", value: "Chemical EOR"},
    { proprty: "EOR Sub Type", value: "Polymer"},
    { proprty: "Flood Type", value: ""},
    { proprty: "Number of Wells", value: 14},
    { proprty: "Number of EOR Injectors", value: 3},
    { proprty: "Number of EOR Producers", value: 11},
    { proprty: "Date", value: ""},
    { proprty: "Discovery Date", value: ""},
    { proprty: "EOR start year", value: 1988},
    { proprty: "Secondary Recovery", value: "Waterflood"},
    { proprty: "EOR 1", value: "Polymer Flood"},
    { proprty: "EOR 2", value: ""},
    { proprty: "EOR 3", value: ""},
    { proprty: "EOR 4", value: ""},
    { proprty: "Reservoir Fluid Properties and Reservoir Parameters", value: ""},
    { proprty: "Depth (m)", value: ""},
    { proprty: "Average Pay Thickness (m)", value: ""},
    { proprty: "Average Permeability (md)", value: ""},
    { proprty: "Average Porosity", value: ""},
    { proprty: "Water Saturation", value: ""},
    { proprty: "Lithology", value: "Sandstone"},
    { proprty: "Initial Pressure (kPa)", value: ""},
    { proprty: "Initial Temperature (C)", value: 24},
    { proprty: "Oil Gravity (API)", value: 21.1},
    { proprty: "Oil Density (kg/m3)", value: 927.3},
    { proprty: "Oil Viscosity @ 15C (cp)", value: 204.95},
    { proprty: "Oil Viscosity @ Tr (cp)", value: 115.27},
    { proprty: "Salinity of Formation Water (ppm)", value: 87000},
    { proprty: "Presence of Natural Fractures", value: ""},
    { proprty: "Presence of Gas Cap", value: "Yes"},
    { proprty: "", value: ""},
    { proprty: "Oil Reserves (as of Dec 31, 2010)", value: ""},
    { proprty: "Area of Project (ha)", value: 194.25},
    { proprty: "Primary Recovery Factor (fraction)", value: ""},
    { proprty: "Incremental WF Recovery Factor (fraction)", value: ""},
    { proprty: "Incremental EOR Recovery Factor (fraction)", value: ""},
    { proprty: "Total Recovery Factor (fraction)", value: ""},
    { proprty: "OOIP (E3m3)", value: ""},
    { proprty: "Remaining Oil in-Place (E3m3) after Primary & EOR Recovery", value: ""},
    { proprty: "Remaining Recoverable Reserves (E3m3)", value: ""},
    ],
    [{proprty: "Field", value: "Countess"},    
    { proprty: "Pool Name", value: "Upper Mannville H"},
    { proprty: "Formation", value: "Upper Mannville H"},
    { proprty: "country", value: "Canada"},
    { proprty: "EOR Type", value: "Chemical EOR"},
    { proprty: "EOR Sub Type", value: "Polymer"},
    { proprty: "Flood Type", value: ""},
    { proprty: "Number of Wells", value: 48},
    { proprty: "Number of EOR Injectors", value: 7},
    { proprty: "Number of EOR Producers", value: ""},
    { proprty: "Date", value: ""},
    { proprty: "Discovery Date", value: 1968},
    { proprty: "EOR start year", value: 1968},
    { proprty: "Secondary Recovery", value: ""},
    { proprty: "EOR 1", value: "Polymer Flood"},
    { proprty: "EOR 2", value: ""},
    { proprty: "EOR 3", value: ""},
    { proprty: "EOR 4", value: ""},
    { proprty: "Reservoir Fluid Properties and Reservoir Parameters", value: ""},
    { proprty: "Depth (m)", value: 1062.5},
    { proprty: "Average Pay Thickness (m)", value: 5.28},
    { proprty: "Average Permeability (md)", value: 945},
    { proprty: "Average Porosity", value: 0.218},
    { proprty: "Water Saturation", value: 0.22},
    { proprty: "Lithology", value: "Sandstone"},
    { proprty: "Initial Pressure (kPa)", value: 8234},
    { proprty: "Initial Temperature (C)", value: 32},
    { proprty: "Oil Gravity (API)", value: 26},
    { proprty: "Oil Density (kg/m3)", value: 898.4},
    { proprty: "Oil Viscosity @ 15C (cp)", value: 49.34},
    { proprty: "Oil Viscosity @ Tr (cp)", value: 23.00},
    { proprty: "Salinity of Formation Water (ppm)", value: 9704},
    { proprty: "Presence of Natural Fractures", value: "NO"},
    { proprty: "Presence of Gas Cap", value: "NO"},
    { proprty: "", value: ""},
    { proprty: "Oil Reserves (as of Dec 31, 2010)", value: ""},
    { proprty: "Area of Project (ha)", value: 710},
    { proprty: "Primary Recovery Factor (fraction)", value: 0.105},
    { proprty: "Incremental WF Recovery Factor (fraction)", value: ""},
    { proprty: "Incremental EOR Recovery Factor (fraction)", value: 0.36},
    { proprty: "Total Recovery Factor (fraction)", value: ""},
    { proprty: "OOIP (E3m3)", value: 5725},
    { proprty: "Remaining Oil in-Place (E3m3) after Primary & EOR Recovery", value: 3253.7},
    { proprty: "Remaining Recoverable Reserves (E3m3)", value: 190.8},
    ],
    [{proprty: "Field", value: ""},    
    { proprty: "Pool Name", value: ""},
    { proprty: "Formation", value: ""},
    { proprty: "country", value: "Canada"},
    { proprty: "EOR Type", value: "Chemical EOR"},
    { proprty: "EOR Sub Type", value: ""},
    { proprty: "Flood Type", value: ""},
    { proprty: "Number of Wells", value: ""},
    { proprty: "Number of EOR Injectors", value: ""},
    { proprty: "Number of EOR Producers", value: ""},
    { proprty: "Date", value: ""},
    { proprty: "Discovery Date", value: ""},
    { proprty: "EOR start year", value: ""},
    { proprty: "Secondary Recovery", value: ""},
    { proprty: "EOR 1", value: ""},
    { proprty: "EOR 2", value: ""},
    { proprty: "EOR 3", value: ""},
    { proprty: "EOR 4", value: ""},
    { proprty: "Reservoir Fluid Properties and Reservoir Parameters", value: ""},
    { proprty: "Depth (m)", value: ""},
    { proprty: "Average Pay Thickness (m)", value: ""},
    { proprty: "Average Permeability (md)", value: ""},
    { proprty: "Average Porosity", value: ""},
    { proprty: "Water Saturation", value: ""},
    { proprty: "Lithology", value: ""},
    { proprty: "Initial Pressure (kPa)", value: ""},
    { proprty: "Initial Temperature (C)", value: ""},
    { proprty: "Oil Gravity (API)", value: ""},
    { proprty: "Oil Density (kg/m3)", value: ""},
    { proprty: "Oil Viscosity @ 15C (cp)", value: ""},
    { proprty: "Oil Viscosity @ Tr (cp)", value: ""},
    { proprty: "Salinity of Formation Water (ppm)", value: ""},
    { proprty: "Presence of Natural Fractures", value: ""},
    { proprty: "Presence of Gas Cap", value: "Yes"},
    { proprty: "", value: ""},
    { proprty: "Oil Reserves (as of Dec 31, 2010)", value: ""},
    { proprty: "Area of Project (ha)", value: ""},
    { proprty: "Primary Recovery Factor (fraction)", value: ""},
    { proprty: "Incremental WF Recovery Factor (fraction)", value: ""},
    { proprty: "Incremental EOR Recovery Factor (fraction)", value: ""},
    { proprty: "Total Recovery Factor (fraction)", value: ""},
    { proprty: "OOIP (E3m3)", value: ""},
    { proprty: "Remaining Oil in-Place (E3m3) after Primary & EOR Recovery", value: ""},
    { proprty: "Remaining Recoverable Reserves (E3m3)", value: ""},
    ],
    [{proprty: "Field", value: ""},    
    { proprty: "Pool Name", value: ""},
    { proprty: "Formation", value: ""},
    { proprty: "country", value: "Canada"},
    { proprty: "EOR Type", value: "Chemical EOR"},
    { proprty: "EOR Sub Type", value: ""},
    { proprty: "Flood Type", value: ""},
    { proprty: "Number of Wells", value: ""},
    { proprty: "Number of EOR Injectors", value: ""},
    { proprty: "Number of EOR Producers", value: ""},
    { proprty: "Date", value: ""},
    { proprty: "Discovery Date", value: ""},
    { proprty: "EOR start year", value: ""},
    { proprty: "Secondary Recovery", value: ""},
    { proprty: "EOR 1", value: ""},
    { proprty: "EOR 2", value: ""},
    { proprty: "EOR 3", value: ""},
    { proprty: "EOR 4", value: ""},
    { proprty: "Reservoir Fluid Properties and Reservoir Parameters", value: ""},
    { proprty: "Depth (m)", value: ""},
    { proprty: "Average Pay Thickness (m)", value: ""},
    { proprty: "Average Permeability (md)", value: ""},
    { proprty: "Average Porosity", value: ""},
    { proprty: "Water Saturation", value: ""},
    { proprty: "Lithology", value: ""},
    { proprty: "Initial Pressure (kPa)", value: ""},
    { proprty: "Initial Temperature (C)", value: ""},
    { proprty: "Oil Gravity (API)", value: ""},
    { proprty: "Oil Density (kg/m3)", value: ""},
    { proprty: "Oil Viscosity @ 15C (cp)", value: ""},
    { proprty: "Oil Viscosity @ Tr (cp)", value: ""},
    { proprty: "Salinity of Formation Water (ppm)", value: ""},
    { proprty: "Presence of Natural Fractures", value: ""},
    { proprty: "Presence of Gas Cap", value: "Yes"},
    { proprty: "", value: ""},
    { proprty: "Oil Reserves (as of Dec 31, 2010)", value: ""},
    { proprty: "Area of Project (ha)", value: ""},
    { proprty: "Primary Recovery Factor (fraction)", value: ""},
    { proprty: "Incremental WF Recovery Factor (fraction)", value: ""},
    { proprty: "Incremental EOR Recovery Factor (fraction)", value: ""},
    { proprty: "Total Recovery Factor (fraction)", value: ""},
    { proprty: "OOIP (E3m3)", value: ""},
    { proprty: "Remaining Oil in-Place (E3m3) after Primary & EOR Recovery", value: ""},
    { proprty: "Remaining Recoverable Reserves (E3m3)", value: ""},
    ],
    
    ]
    
  ]
export {columnDefs,rowDatachemical};
